### ISSUE TITLE
User Interface Mockups and Storyboard Sequences

### ISSUE THREAD

**Issue by chris-vanderveen** [CMPUT301W24T08/DroidDesign#10]
Diagram the layout of your main user interface and major dialogs, with comments describing the important elements. Also, diagram storyboard sequences of using your application, with transitions between different states of the user interface, caused by the user manipulating the controls or providing input. Within the diagrams, reference the relevant requirements. Convincingly show all the requirements are covered.

**Acceptance Criteria**

- [x] Mockups display all key app screens including login, event creation, QR code scanning, and real-time dashboard, with clearly labeled UI elements.

- [x] Storyboards depict critical user actions and transitions for both organizers and attendees, highlighting event creation, sign-up, QR code check-in, and notification management.

- [x] Each mockup and storyboard frame includes detailed comments explaining the purpose of UI elements and expected user interactions.

- [x] Designs comprehensively address every project feature such as QR code functionality, Firebase integration, role-based access, optional geolocation verification, and image uploads.

- [x] UI design is consistent across all screens with an intuitive layout, following a unified color scheme and typography for user-friendliness.

- [x] Designs demonstrate flexibility for future updates and feature additions, ensuring scalability.

- [x] Interactive elements like buttons for event sign-up and receiving notifications are included to enhance user engagement.

- [x] The designs are validated against described scenarios, effectively showing how the app supports event management and attendee check-in processes.

**Comment by samad-zeeshan** [comment]
Completed Story Boards and User Interface Layouts!
