### ISSUE TITLE
Implement QR Code Scanning Feature

### ISSUE THREAD

**Issue by chris-vanderveen** [CMPUT301W24T08/DroidDesign#12]
Attendees can use the app to scan event-specific QR codes for quick and seamless check-ins.

**Acceptance Criteria**

- [x] Attendees can easily access the QR code scanning feature within the app with clear instructions on how to proceed.

- [x] The app quickly and accurately recognizes event-specific QR codes using the camera.

- [x] Upon scanning, the app verifies that the QR code corresponds to a valid, active event.

- [x] If the QR code is valid, the attendee is automatically checked into the event, and a confirmation message is displayed.

- [x]  If the QR code is not recognized or does not correspond to an active event, the app displays an informative error message and suggests next steps.

- [x] The scanning and check-in process completes within a few seconds to ensure a seamless experience for the attendee.

- [x] The attendee's check-in status is updated in real-time in the event organizer's dashboard and the attendee's event history.

**Comment by ayokunle321** [comment]
Completed

**Comment by ayokunle321** [comment]
Completed
